services:
  postgres:
    image: postgres:16
    container_name: globalpay-postgres
    environment:
      POSTGRES_DB: globalpay
      POSTGRES_USER: globalpay
      POSTGRES_PASSWORD: globalpay_dev_only
    ports:
      - "5432:5432"
    volumes:
      - globalpay_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U globalpay -d globalpay"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  globalpay_postgres_data:
